import { v4 as uuidv4 } from "uuid"

export const filters = [
  {
    id: uuidv4(),
    name: "Size",
    optionType: "size",
    optionValue: "Small",
    active: false,
    count: 0,
    products: [],
  },
  {
    id: uuidv4(),
    name: "Size",
    optionType: "size",
    optionValue: "Medium",
    active: false,
    count: 0,
    products: [],
  },
  {
    id: uuidv4(),
    name: "Size",
    optionType: "size",
    optionValue: "Large",
    active: false,
    count: 0,
    products: [],
  },
  {
    id: uuidv4(),
    name: "Color",
    optionType: "color",
    optionValue: "Red",
    active: false,
    count: 0,
    products: [],
  },
  {
    id: uuidv4(),
    name: "Color",
    optionType: "color",
    optionValue: "Green",
    active: false,
    count: 0,
    products: [],
  },
  {
    id: uuidv4(),
    name: "Color",
    optionType: "color",
    optionValue: "Blue",
    active: false,
    count: 0,
    products: [],
  },
]
