export const products = [
  {
    title: "Adidas",
    date: "2020-05-07",
    price: 10.3,
    sku: "W01",
    color: [{ value: "Red" }, { value: "Green" }],
    size: [{ value: "Large" }, { value: "Small" }],
  },
  {
    title: "Jack & Jones",
    date: "2020-02-01",
    price: 20.18,
    sku: "W02",
    color: [{ value: "Red" }, { value: "Blue" }],
    size: [{ value: "Medium" }],
    offer: true,
  },

  {
    title: "BOSS",
    date: "2020-04-06",
    price: 30.72,
    sku: "W06",
    color: [{ value: "Blue" }, { value: "Green" }],
    size: [{ value: "Medium" }, { value: "Large" }],
  },
  {
    title: "Gucci",
    date: "2020-08-11",
    price: 40.26,
    sku: "W05",
    color: [{ value: "Red" }],
    size: [{ value: "Medium" }, { value: "Large" }],
    offer: true,
  },
  {
    title: "Diesel",
    date: "2020-07-10",
    price: 50.22,
    sku: "W04",
    color: [{ value: "Green" }],
    size: [{ value: "Medium" }, { value: "Large" }],
  },
  {
    title: "Nike",
    date: "2020-06-07",
    price: 60.18,
    sku: "W03",
    // filter: [{ id: "FEFIJOE343H", name: "Color", value: ["Blue", "Red"] }],
    color: [{ value: "Blue" }],
    size: [{ value: "Medium" }],
  },
]
